[application]

[web.app]
title = "Akhsakov Finance"

[web.resource]
style = []
script = []

[web.resource.dev]
script = []

[bundle]
identifier = "com.akhsakov.finance"
publisher = "Akhsakov"
short_description = "Personal finance application"
category = "Finance"
